version: '3.8' 


x-class_volumes: &class_volumes
    - ./sta2453-project-files:/home/app_user/app/
      # mount all files in current directory to home app user. 

services:
    
    shell_sta2453: &shell_sta2453
        <<: *shell_sta2453
        image: shell_sta2453 
        container_name: shell_sta2453
        build: 
            context: .
            target: shell_sta2453
            dockerfile: ./Dockerfile
        volumes: *class_volumes

